export const UserData = [
  {
    key: "1",
    name: "Ramy Mohsen",
    UserName: "ramy.mohsen",
    EmailAddress: "ramy.mohsen@gogle.com",
    Group: "Office",
    Status: "Locked",
    Creaton: "Dec 10,2022",
  },
  {
    key: "2",
    name: "Hisham Hagag",
    UserName: "hisham.hagag",
    EmailAddress: "hisham.hagag@like.com",
    Group: "Managers",
    Status: "Inactive",
    Creaton: "Oct 22,2018",
  },
  {
    key: "3",
    name: "Khaled Adam",
    UserName: "khaled.adam",
    EmailAddress: "khaled.adam@like.com",
    Group: "Office",
    Status: "Active",
    Creaton: "Oct 15,2018",
  },
  {
    key: "4",
    name: "كريم فاروق",
    UserName: "kareem.farouk",
    EmailAddress: "kareem.farouk@nuvb.net",
    Group: "Office",
    Status: "Active",
    Creaton: "Jun 17,2022",
  },
  {
    key: "5",
    name: "Nour Hamdy",
    UserName: "nour.hamdy",
    EmailAddress: "nour.hamdy@lisi.com",
    Group: "Managers",
    Status: "Active",
    Creaton: "Sep 9,2019",
  },
  {
    key: "6",
    name: "حنان فوزي",
    UserName: "hanan.fawzy",
    EmailAddress: "hanan.fawzy@buno.net",
    Group: "Head Office",
    Status: "Active",
    Creaton: "Sep 21,2022",
  },
  {
    key: "7",
    name: "ايمان ادم",
    UserName: "iman.adam",
    EmailAddress: "iman.adam@fadok.net",
    Group: "Office",
    Status: "Active",
    Creaton: "Dec 27,2022",
  },
  {
    key: "8",
    name: "Mayar Farouq",
    UserName: "mayar.farouq",
    EmailAddress: "mayar.farouq@share.net",
    Group: "Head Office",
    Status: "Active",
    Creaton: "Feb 14,2022",
  },
];
